//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.06 at 06:29:18 AM MSK 
//


package smevsign.smev.v1_2;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * 
 *                 Ссылка на файл, приложенный к СМЭВ-сообщению.
 *             
 * 
 * <p>Java class for RefAttachmentHeaderType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RefAttachmentHeaderType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="uuid" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Hash" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="MimeType" type="{urn://x-artefacts-smev-gov-ru/services/message-exchange/types/basic/1.2}RFC2046MimeTypesType"/&gt;
 *         &lt;element name="SignaturePKCS7" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RefAttachmentHeaderType", namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/basic/1.2", propOrder = {
    "uuid",
    "hash",
    "mimeType",
    "signaturePKCS7"
})
public class RefAttachmentHeaderType {

    @XmlElement(required = true)
    protected String uuid;
    @XmlElement(name = "Hash", required = true)
    protected String hash;
    @XmlElement(name = "MimeType", required = true)
    protected String mimeType;
    @XmlElement(name = "SignaturePKCS7")
    protected byte[] signaturePKCS7;

    /**
     * Gets the value of the uuid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * Sets the value of the uuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUuid(String value) {
        this.uuid = value;
    }

    /**
     * Gets the value of the hash property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHash() {
        return hash;
    }

    /**
     * Sets the value of the hash property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHash(String value) {
        this.hash = value;
    }

    /**
     * Gets the value of the mimeType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMimeType() {
        return mimeType;
    }

    /**
     * Sets the value of the mimeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMimeType(String value) {
        this.mimeType = value;
    }

    /**
     * Gets the value of the signaturePKCS7 property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getSignaturePKCS7() {
        return signaturePKCS7;
    }

    /**
     * Sets the value of the signaturePKCS7 property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setSignaturePKCS7(byte[] value) {
        this.signaturePKCS7 = value;
    }

}
