//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.06 at 06:29:15 AM MSK 
//


package smevsign.smev.v1_3;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="OriginalMessageId" type="{urn://x-artefacts-smev-gov-ru/services/message-exchange/types/basic/1.3}UUID"/&gt;
 *         &lt;element name="StatusCategory" type="{urn://x-artefacts-smev-gov-ru/services/message-exchange/types/basic/1.3}InteractionStatusType"/&gt;
 *         &lt;element name="StatusDetails" type="{urn://x-artefacts-smev-gov-ru/services/message-exchange/types/basic/1.3}string-500" minOccurs="0"/&gt;
 *         &lt;element ref="{urn://x-artefacts-smev-gov-ru/services/message-exchange/types/routing/1.3}RoutingStatus" minOccurs="0"/&gt;
 *         &lt;element name="SmevFault" type="{urn://x-artefacts-smev-gov-ru/services/message-exchange/types/basic/1.3}SmevFault" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "originalMessageId",
    "statusCategory",
    "statusDetails",
    "routingStatus",
    "smevFault"
})
@XmlRootElement(name = "AsyncProcessingStatus")
public class AsyncProcessingStatus {

    @XmlElement(name = "OriginalMessageId", required = true)
    protected String originalMessageId;
    @XmlElement(name = "StatusCategory", required = true)
    @XmlSchemaType(name = "string")
    protected InteractionStatusType statusCategory;
    @XmlElement(name = "StatusDetails")
    protected String statusDetails;
    @XmlElement(name = "RoutingStatus", namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/routing/1.3")
    protected RoutingStatus routingStatus;
    @XmlElement(name = "SmevFault")
    protected SmevFault smevFault;

    /**
     * Gets the value of the originalMessageId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginalMessageId() {
        return originalMessageId;
    }

    /**
     * Sets the value of the originalMessageId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginalMessageId(String value) {
        this.originalMessageId = value;
    }

    /**
     * Gets the value of the statusCategory property.
     * 
     * @return
     *     possible object is
     *     {@link InteractionStatusType }
     *     
     */
    public InteractionStatusType getStatusCategory() {
        return statusCategory;
    }

    /**
     * Sets the value of the statusCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link InteractionStatusType }
     *     
     */
    public void setStatusCategory(InteractionStatusType value) {
        this.statusCategory = value;
    }

    /**
     * Gets the value of the statusDetails property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatusDetails() {
        return statusDetails;
    }

    /**
     * Sets the value of the statusDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatusDetails(String value) {
        this.statusDetails = value;
    }

    /**
     * Статус маршрутизации сообщения
     * 
     * @return
     *     possible object is
     *     {@link RoutingStatus }
     *     
     */
    public RoutingStatus getRoutingStatus() {
        return routingStatus;
    }

    /**
     * Sets the value of the routingStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link RoutingStatus }
     *     
     */
    public void setRoutingStatus(RoutingStatus value) {
        this.routingStatus = value;
    }

    /**
     * Gets the value of the smevFault property.
     * 
     * @return
     *     possible object is
     *     {@link SmevFault }
     *     
     */
    public SmevFault getSmevFault() {
        return smevFault;
    }

    /**
     * Sets the value of the smevFault property.
     * 
     * @param value
     *     allowed object is
     *     {@link SmevFault }
     *     
     */
    public void setSmevFault(SmevFault value) {
        this.smevFault = value;
    }

}
