//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.06 at 06:29:15 AM MSK 
//

@jakarta.xml.bind.annotation.XmlSchema(
        namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/1.3",
        xmlns = {
                @jakarta.xml.bind.annotation.XmlNs(
                        prefix = "ns", namespaceURI = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/1.3"
                )
        },
        elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED
)
package smevsign.smev.v1_3;
