//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.06 at 06:29:15 AM MSK 
//


package smevsign.smev.v1_3;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlID;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{urn://x-artefacts-smev-gov-ru/services/message-exchange/types/directive/1.3}RecordContent"/&gt;
 *         &lt;element ref="{urn://x-artefacts-smev-gov-ru/services/message-exchange/types/basic/1.3}AttachmentHeaderList" minOccurs="0"/&gt;
 *         &lt;element ref="{urn://x-artefacts-smev-gov-ru/services/message-exchange/types/basic/1.3}RefAttachmentHeaderList" minOccurs="0"/&gt;
 *         &lt;element name="PersonalSignature" type="{urn://x-artefacts-smev-gov-ru/services/message-exchange/types/basic/1.3}XMLDSigSignatureType" maxOccurs="10" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="Id" type="{http://www.w3.org/2001/XMLSchema}ID" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "recordContent",
    "attachmentHeaderList",
    "refAttachmentHeaderList",
    "personalSignature"
})
@XmlRootElement(name = "Record", namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/directive/1.3")
public class Record {

    @XmlElement(name = "RecordContent", namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/directive/1.3", required = true)
    protected RecordContent recordContent;
    @XmlElement(name = "AttachmentHeaderList", namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/basic/1.3")
    protected AttachmentHeaderList attachmentHeaderList;
    @XmlElement(name = "RefAttachmentHeaderList", namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/basic/1.3")
    protected RefAttachmentHeaderList refAttachmentHeaderList;
    @XmlElement(name = "PersonalSignature", namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/directive/1.3")
    protected List<XMLDSigSignatureType> personalSignature;
    @XmlAttribute(name = "Id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;

    /**
     * Gets the value of the recordContent property.
     * 
     * @return
     *     possible object is
     *     {@link RecordContent }
     *     
     */
    public RecordContent getRecordContent() {
        return recordContent;
    }

    /**
     * Sets the value of the recordContent property.
     * 
     * @param value
     *     allowed object is
     *     {@link RecordContent }
     *     
     */
    public void setRecordContent(RecordContent value) {
        this.recordContent = value;
    }

    /**
     * Заголовки вложенных файлов.
     * 
     * @return
     *     possible object is
     *     {@link AttachmentHeaderList }
     *     
     */
    public AttachmentHeaderList getAttachmentHeaderList() {
        return attachmentHeaderList;
    }

    /**
     * Sets the value of the attachmentHeaderList property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttachmentHeaderList }
     *     
     */
    public void setAttachmentHeaderList(AttachmentHeaderList value) {
        this.attachmentHeaderList = value;
    }

    /**
     * Заголовки файлов по ссылке.
     * 
     * @return
     *     possible object is
     *     {@link RefAttachmentHeaderList }
     *     
     */
    public RefAttachmentHeaderList getRefAttachmentHeaderList() {
        return refAttachmentHeaderList;
    }

    /**
     * Sets the value of the refAttachmentHeaderList property.
     * 
     * @param value
     *     allowed object is
     *     {@link RefAttachmentHeaderList }
     *     
     */
    public void setRefAttachmentHeaderList(RefAttachmentHeaderList value) {
        this.refAttachmentHeaderList = value;
    }

    /**
     * Gets the value of the personalSignature property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the personalSignature property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPersonalSignature().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link XMLDSigSignatureType }
     * 
     * 
     */
    public List<XMLDSigSignatureType> getPersonalSignature() {
        if (personalSignature == null) {
            personalSignature = new ArrayList<XMLDSigSignatureType>();
        }
        return this.personalSignature;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
