//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.06 at 06:29:15 AM MSK 
//


package smevsign.smev.v1_3;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RejectCode.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="RejectCode"&gt;
 *   &lt;restriction base="{urn://x-artefacts-smev-gov-ru/services/message-exchange/types/basic/1.3}string-50"&gt;
 *     &lt;enumeration value="ACCESS_DENIED"/&gt;
 *     &lt;enumeration value="NO_DATA"/&gt;
 *     &lt;enumeration value="UNKNOWN_REQUEST_DESCRIPTION"/&gt;
 *     &lt;enumeration value="FAILURE"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "RejectCode")
@XmlEnum
public enum RejectCode {

    ACCESS_DENIED,
    NO_DATA,
    UNKNOWN_REQUEST_DESCRIPTION,
    FAILURE;

    public String value() {
        return name();
    }

    public static RejectCode fromValue(String v) {
        return valueOf(v);
    }

}
