//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.06 at 06:29:15 AM MSK 
//


package smevsign.smev.v1_3;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlID;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * Параметры маршрутизации сообщения
 * 
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="MessageID" type="{urn://x-artefacts-smev-gov-ru/services/message-exchange/types/basic/1.3}UUID"/&gt;
 *         &lt;element ref="{urn://x-artefacts-smev-gov-ru/services/message-exchange/types/routing/1.3}DynamicRouting" minOccurs="0"/&gt;
 *         &lt;element ref="{urn://x-artefacts-smev-gov-ru/services/message-exchange/types/routing/1.3}IdentifierRouting" minOccurs="0"/&gt;
 *         &lt;element ref="{urn://x-artefacts-smev-gov-ru/services/message-exchange/types/routing/1.3}RegistryRouting" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="Id" type="{http://www.w3.org/2001/XMLSchema}ID" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "messageID",
    "dynamicRouting",
    "identifierRouting",
    "registryRouting"
})
@XmlRootElement(name = "RoutingInformation", namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/routing/1.3")
public class RoutingInformation {

    @XmlElement(name = "MessageID", namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/routing/1.3", required = true)
    protected String messageID;
    @XmlElement(name = "DynamicRouting", namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/routing/1.3")
    protected DynamicRouting dynamicRouting;
    @XmlElement(name = "IdentifierRouting", namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/routing/1.3")
    protected IdentifierRouting identifierRouting;
    @XmlElement(name = "RegistryRouting", namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/routing/1.3")
    protected RegistryRouting registryRouting;
    @XmlAttribute(name = "Id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;

    /**
     * Gets the value of the messageID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessageID() {
        return messageID;
    }

    /**
     * Sets the value of the messageID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessageID(String value) {
        this.messageID = value;
    }

    /**
     * Gets the value of the dynamicRouting property.
     * 
     * @return
     *     possible object is
     *     {@link DynamicRouting }
     *     
     */
    public DynamicRouting getDynamicRouting() {
        return dynamicRouting;
    }

    /**
     * Sets the value of the dynamicRouting property.
     * 
     * @param value
     *     allowed object is
     *     {@link DynamicRouting }
     *     
     */
    public void setDynamicRouting(DynamicRouting value) {
        this.dynamicRouting = value;
    }

    /**
     * Gets the value of the identifierRouting property.
     * 
     * @return
     *     possible object is
     *     {@link IdentifierRouting }
     *     
     */
    public IdentifierRouting getIdentifierRouting() {
        return identifierRouting;
    }

    /**
     * Sets the value of the identifierRouting property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentifierRouting }
     *     
     */
    public void setIdentifierRouting(IdentifierRouting value) {
        this.identifierRouting = value;
    }

    /**
     * Gets the value of the registryRouting property.
     * 
     * @return
     *     possible object is
     *     {@link RegistryRouting }
     *     
     */
    public RegistryRouting getRegistryRouting() {
        return registryRouting;
    }

    /**
     * Sets the value of the registryRouting property.
     * 
     * @param value
     *     allowed object is
     *     {@link RegistryRouting }
     *     
     */
    public void setRegistryRouting(RegistryRouting value) {
        this.registryRouting = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
