//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.06 at 06:29:15 AM MSK 
//


package smevsign.smev.v1_3;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RoutingStatusCodeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="RoutingStatusCodeType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="success"/&gt;
 *     &lt;enumeration value="recipientNotFound"/&gt;
 *     &lt;enumeration value="invalidRegistryRecordId"/&gt;
 *     &lt;enumeration value="signatureInvalid"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "RoutingStatusCodeType", namespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/routing/1.3")
@XmlEnum
public enum RoutingStatusCodeType {


    /**
     * Выполнено успешно
     * 
     */
    @XmlEnumValue("success")
    SUCCESS("success"),

    /**
     * Получатель сообщения не найден
     * 
     */
    @XmlEnumValue("recipientNotFound")
    RECIPIENT_NOT_FOUND("recipientNotFound"),

    /**
     * Некорректный идентификатор реестровой записи
     * 
     */
    @XmlEnumValue("invalidRegistryRecordId")
    INVALID_REGISTRY_RECORD_ID("invalidRegistryRecordId"),

    /**
     * Подпись реестровой записи невалидна
     * 
     */
    @XmlEnumValue("signatureInvalid")
    SIGNATURE_INVALID("signatureInvalid");
    private final String value;

    RoutingStatusCodeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static RoutingStatusCodeType fromValue(String v) {
        for (RoutingStatusCodeType c: RoutingStatusCodeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
