//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.06 at 06:29:21 AM MSK 
//


package smevsign.smev.v1_1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;choice&gt;
 *           &lt;element ref="{urn://x-artefacts-smev-gov-ru/services/message-exchange/types/1.1}AsyncProcessingStatusData"/&gt;
 *         &lt;/choice&gt;
 *         &lt;element name="SMEVSignature" type="{urn://x-artefacts-smev-gov-ru/services/message-exchange/types/basic/1.1}XMLDSigSignatureType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "asyncProcessingStatusData",
    "smevSignature"
})
@XmlRootElement(name = "SmevAsyncProcessingMessage")
public class SmevAsyncProcessingMessage {

    @XmlElement(name = "AsyncProcessingStatusData")
    protected AsyncProcessingStatusData asyncProcessingStatusData;
    @XmlElement(name = "SMEVSignature")
    protected XMLDSigSignatureType smevSignature;

    /**
     * Gets the value of the asyncProcessingStatusData property.
     * 
     * @return
     *     possible object is
     *     {@link AsyncProcessingStatusData }
     *     
     */
    public AsyncProcessingStatusData getAsyncProcessingStatusData() {
        return asyncProcessingStatusData;
    }

    /**
     * Sets the value of the asyncProcessingStatusData property.
     * 
     * @param value
     *     allowed object is
     *     {@link AsyncProcessingStatusData }
     *     
     */
    public void setAsyncProcessingStatusData(AsyncProcessingStatusData value) {
        this.asyncProcessingStatusData = value;
    }

    /**
     * Gets the value of the smevSignature property.
     * 
     * @return
     *     possible object is
     *     {@link XMLDSigSignatureType }
     *     
     */
    public XMLDSigSignatureType getSMEVSignature() {
        return smevSignature;
    }

    /**
     * Sets the value of the smevSignature property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLDSigSignatureType }
     *     
     */
    public void setSMEVSignature(XMLDSigSignatureType value) {
        this.smevSignature = value;
    }

}
